### ISSUE TITLE
Feature request: allow specification of "active" animation classes

### ISSUE THREAD

**Issue by bitpshr** [AFASSoftware/maquette#87]
Maquette makes use of an active CSS class during animations, e.g. `.slideUp-active`. This pattern of building the active animation class by appending "-active" to the base animation class is problematic when using [CSS modules](https://github.com/css-modules/css-modules) where class names are translated in order to avoid conflicts.

Consider the following CSS:

```css
.show {
    transition: opacity .2s;
    opacity: 0;
}

.show-active {
    opacity: 1;
}
```
When using CSS modules, these classes are translated to unique, locally-scoped class names, usually based on the hash of the selector:

```css
._2ImYJCTW {
    transition: opacity .2s;
    opacity: 0;
}

.ik3ej5vm {
    opacity: 1;
}
```
If the base animation class for a node is specified as `._2ImYJCTW `, the active animation class generated by Maquette will be `._2ImYJCTW-active`, which isn't valid because `.show-active` is translated to `.ik3ej5vm`.

A possible fix would be to allow an active enter and active exit animation class to be specified when creating a node.
